// part and slotted not currently supported by quarks
const PSEUDO_ELEMENTS = [
  // '::part()',
  // '::slotted()',
  '::after',
  '::backdrop',
  '::before',
  '::cue',
  '::cue-region',
  '::first-letter',
  '::first-line',
  '::file-selector-button',
  '::grammar-error',
  '::marker',
  '::placeholder',
  '::selection',
  '::spelling-error',
  '::target-text',
  '::-moz-placeholder',
  '::-moz-progress-bar',
  '::-moz-range-progress',
  '::-moz-range-thumb',
  '::-moz-range-track',
  '::-moz-selection',
  '::-ms-backdrop',
  '::-ms-browse',
  '::-ms-check',
  '::-ms-clear',
  '::-ms-expand',
  '::-ms-fill',
  '::-ms-fill-lower',
  '::-ms-fill-upper',
  '::-ms-input-placeholder',
  '::-ms-reveal',
  '::-ms-thumb',
  '::-ms-ticks-after',
  '::-ms-ticks-before',
  '::-ms-tooltip',
  '::-ms-track',
  '::-ms-value',
  '::-webkit-backdrop',
  '::-webkit-input-placeholder',
  '::-webkit-progress-bar',
  '::-webkit-progress-inner-value',
  '::-webkit-progress-value',
  '::-webkit-slider-runnable-track',
  '::-webkit-slider-thumb',
];

export const prefixedPseudoElements = PSEUDO_ELEMENTS.map(pseudoEle => pseudoEle.replace('::', '$'));

export default PSEUDO_ELEMENTS;
